### ISSUE TITLE
typos in tests for factory

### ISSUE THREAD

**Issue by fetsorn** [Gravity-Tech/gravity-core#53]
"invaid" should be "inva**l**id"
https://github.com/Gravity-Tech/gravity-core/blob/073ad1fe4e70c462994da275bbb263f838b62850/common/adaptors/waves_test.go#L39
"adoptor" should be "adaptor"
https://github.com/Gravity-Tech/gravity-core/blob/073ad1fe4e70c462994da275bbb263f838b62850/common/adaptors/factory_test.go#L115
@akriventsev

**Comment by akriventsev** [comment]
Fixed
