### ISSUE TITLE
ledger init generates wrong waves address 

### ISSUE THREAD

**Issue by fetsorn** [Gravity-Tech/gravity-core#68]
`gravity ledger init` generates wrong address for node's identity on waves. In privKey.json the TargetChains.waves.Address value is not the seed's address on mainnet but some broken address.

**Comment by sham789** [comment]
you should provide --network parameter (either `mainnet` or `customnet`)

**Comment by fetsorn** [comment]
TIL. I used to fix it manually. Will use `--network` now. Thanks!
